### ISSUE TITLE
Create new BITS (Bridge Inundation Threat Service) (BFT)

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/hydrovis#864]
Create a new service which shows bridges and can show the user one of three colors to define the threat of flooding for it.  

For 2.1.8, we added a new "bridge centroid" static system which is just points of where bridges are at. The Bridge Centroids System wil continue unaltered as before other than how manual_downloads populates the table. Otherwise, this is a new independant set of services.

Details are still pending, but generally:
- Usability
     - A green color will be shown if the bridge is not under threat.  Yellow if the flow data is within 75% of the ___ " and Red if it is inundated.
- It will follow all of the QC/ FIM FIMPact related forecast services similar to building services

- From the fim dev team, this system will load the files named "osm_bridge_centroid.gpkg" files at the HUC level same as it did for the original Bridge Centriods system but now with some new fields.

---------
**Update: Feb 3, 2025**
- This card will be updated as steps evolve and soem of the larger tasks may trigger child cards.

---------
**Update: Mar 26, 2025**
- renamed from BITS to BFT (Bridge Flood Threat) service.

### Tasks

- [x] Design loading of data of the bridge data from HAND into a new RDS db. The data will not change for the entire release so it can be in RDS. 
- [x] Sort out DB fields and service fields. Note: not all of the fields coming from FIM dev for each HUC need to be loaded here. And, some of the fields we do load into HV will not be available to the service but are kept for reference purposes.
- [x] Build HV data load system (manual workflows system) 
- [x] Build Mapx for each service- in progress
- [x] Following buildings for FIMPact, add to each of the same layers (sql and yaml files). - in progress
- [x] Integrate to HV pipeline flows as part of the FIM pipeline system.
- [x] Watch for duplicate points (by OSM?), adjust to highest threat for overlapping points.
- [ ] We are keeping the old static Bridge service and it can share the new bridge_points db. Can the git code to point to the new table for it's datasource.
