### ISSUE TITLE
2.1.8 (FIM 5.1) - Deployment Checklist

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/hydrovis#958]
# TI

## Data Inputs Received
- [x] HAND
- [x] ras2fim / Ripple  (n/a - no new data for this release)
- [x] FIM Performance
- [x] Catfim Stage Data
- [x] Catfim Flow Data
- [x] usgs rating curve
- [x] agg_nwm_recurr flows

## Data Ingests/Loads
- [x] Crosswalk
- [x] ras2fim Model  (just adjust table to add model_version field)
- [x] ras2fim (no new data load required)
- [x] ras2fim Boundaries  (n/a for this release)
- [x] AEP 
- [x] Catchments - Branch 0
- [x] Catchments - GMS
- [x] USGS Elev Table
- [x] Hydrotable - staggered
- [x] usgs rating curve - staggered
- [x] Skill Metrics
- [x] FIM Performance
- [x] CatFIM Stage
- [x] CatFIM Stage - FIM 30
- [x] CatFIM Flow
- [x] Bridge Centroids
- [x] Clear HAND cache
- [x] Push injest code to GIT / TF

## QA/QC
- [x] Run "hv-vpp-ti-trigger-apocalyptic-tests" Step Function without errors
- [x] Run "Core\Manual_Workflows\Align MAPX dtypes with DB.ipynb" Notebook and commit/PR/merge any changes
- [x] Run "Core\Manual_Workflows\helper_functions\sync_services_with_master_list.py" and commit/PR/merge any changes

(Add steps here, if they come up, to manually check services)

-----------------------------------

## Dump and move tables to S3

These are done using the "hv-vpp-ti-db-dumps-to-s3" Step Function.

### EGIS tables

- [x] AEP  (egis)
    - aep_fim.rf_2_inundation
    - aep_fim.rf_5_inundation
    - aep_fim.rf_10_inundation
    - aep_fim.rf_25_inundation
    - aep_fim.rf_50_inundation
    - aep_fim.rf_high_water_inundation
- [x] AEP Alaska (egis)
    - aep_fim.rf_2_inundation_ak
    - aep_fim.rf_5_inundation_ak
    - aep_fim.rf_10_inundation_ak
    - aep_fim.rf_25_inundation_ak
    - aep_fim.rf_50_inundation_ak
    - aep_fim.rf_high_water_inundation_ak
- [x] Catchments - branch 0  (egis) 
    - fim_catchments.catchments_0_branches
    - fim_catchments.catchments_0_branches_hi
    - fim_catchments.catchments_0_branches_prvi
    - **Note:** These three databases have been renamed slightly, moving the word "catchments" to the front from previous versions:
- [x] Catchments - gms branch  (egis)  
    - fim_catchments.catchments_gms_branches    **Problem: Won't load via Step functions**
    - fim_catchments.catchments_gms_branches_hi
    - fim_catchments.catchments_gms_branches_prvi
    - **Note:** These three databases have been renamed slightly, moving the word "catchments" to the front from previous db versions:
- [x] FIM Performance  (egis)
    - reference.fim_performance_polys
    - reference.fim_performance_points
    - reference.fim_performance_catchments
- [x] CatFIM Stage    (egis)
    - reference.stage_based_catfim
    - reference.stage_based_catfim_sites
- [x] CatFIM Flow     (egis)
    - reference.flow_based_catfim
    - reference.flow_based_catfim_sites
- [x] CatFIM Stage - FIM 30    (egis)    (note.. there is no flow based version of this (I think))
     - reference.stage_based_catfim_fim_30
     - reference.stage_based_catfim_sites_fim_30
     - **NOTE:**  These two CatFIM fim 30 sites are DB renames. In earlier versions, the phrase "public" which is now replaced with "fim_30"
- [x] Skills metrics    (egis)  (note: made in viz.derived, but copied over to egis.reference for deployment)
    - reference.src_skill
- [x] Bridge Centroids  (egis)  (needs reloading.. osm_id column is incorrect
    - reference.bridge_centroids  (Note: New service and DB)
- [x] Static Flowline Services
    - reference.channels_ak (dtype change)
    - reference.channels_conus (dtype change)

- [x] DB cleanup script (egis) - give sql script to UAT for cleanup up UAT db;s. ie) dropping old, now renamed tables plus cleaning up old legacy non-realvent tables from previous release (like catfim_public tables), etc.

### VIZ tables

- [x] Crosswalk   (viz)  
    -  derived.fim4_featureid_crosswalk
- [x] ras2fim  (viz)
    -  ras2fim.geocurves (updated and needs data dump)
             Note: ras2fim.max_geocurves was not reloaded and the 4.5.2.11 are still valid
- ras2fim boundaries  ->  **SKIP**. ras2fim.boundaries were not reloaded and the 4.5.2.11 are still valid
- [x] usgs elev  (viz)
    -  derived.usgs_elev_table
- [x] Hydrotable staggered  (viz)
    - derived.hydrotable_staggered
 - [x] usgs rating curves staggered  (viz)
    - derived.usgs_rating_curves_staggered 
- [x] HANDFIM_cache DBs  (viz)
     - handfim_cache.hydrotable_cached
     - handfim_cache.hydrotable_cached_geo
     - handfim_cache.hydrotable_cached_max
     - handfim_cache.hydrotable_cached_zero_stage
- [x] derived.channels_ak (renamed from derived.channels_alaska) : Note: Only needs a reload when a new NWM version comes out.

- [x] DB cleanup script (viz) - give sql script to UAT for cleanup up UAT db;s. ie) dropping old, now renamed tables plus cleaning up old legacy non-realvent tables from previous release (like catfim_public tables), etc.

# UAT

## Pre-Deploy

- [x] Move new FIM version data in S3 to UAT
- [x] Move VIZ DB dump files to UAT
- [x] Move EGIS DB dump files to UAT
- [x] Run VIZ DB cleanup scripts 
- [x] Run EGIS DB cleanup scripts
- [x] [Re]Publish mapxtosd GP service to GP server

## Post-Deploy

- [x] Manually (for now) execute hv-vpp-uat-viz-publish-service Lambda for all new/updated static services
- [x] Manually execute SQL as documented in #1050
- [x] Manually publish all /image services from viz-pipeline EC2 using update_data_stores_and_sd_files.py script

# Prod (US-EAST-1)

## Pre-Deploy

- [x] Move new FIM version data in S3 to Prod
- [x] Move VIZ DB dump files to Prod
- [x] Move EGIS DB dump files to Prod
- [ ] Run VIZ DB cleanup scripts 
- [ ] Run EGIS DB cleanup scripts
- [x] [Re]Publish mapxtosd GP service to GP server

## Post-Deploy

- [x] Verify update_data_stores_and_sd_files.py executed successful on viz-pipeline machine to publish static services 
- [x] Look at /var/log/cloud-init-output.log on rds-bastion machine to veridy DB dumps processed properly
- [x] If #1050 hasn't been completed and its solution code deployed to prod, manually execute SQL as documented in #1050
- [x] Manually publish all /image services from viz-pipeline EC2 using update_data_stores_and_sd_files.py script (if issue not resolved)
- [x] Manually delete published flags for all services that only had service description changed, since they won't be automatically republished.

# Prod (US-EAST-2)

## Pre-Deploy

- [x] Move new FIM version data in S3 to Prod
- [x] Move VIZ DB dump files to Prod
- [x] Move EGIS DB dump files to Prod
- [ ] Run VIZ DB cleanup scripts 
- [ ] Run EGIS DB cleanup scripts
- [x] [Re]Publish mapxtosd GP service to GP server

## Post-Deploy

- [x] Verify update_data_stores_and_sd_files.py executed successful on viz-pipeline machine to publish static services 
- [x] Look at /var/log/cloud-init-output.log on rds-bastion machine to veridy DB dumps processed properly
- [x] If #1050 hasn't been completed and its solution code deployed to prod, manually execute SQL as documented in #1050
- [x] Manually publish all /image services from viz-pipeline EC2 using update_data_stores_and_sd_files.py script (if issue not resolved)
- [x] Manually delete published flags for all services that only had service description changed, since they won't be automatically republished.
